import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
        <link rel="apple-touch-icon" sizes="76x76" href="../assets/img/apple-icon.png"/>
        <link rel="icon" type="image/png" href="/assets/img/favicon.png"/>
        <title>
          Soft UI Dashboard by Creative Tim
        </title>
        {/*      Fonts and icons      */}
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet" />
        {/*  Nucleo Icons  */}
        <link href="/assets/css/nucleo-icons.css" rel="stylesheet" />
        <link href="/assets/css/nucleo-svg.css" rel="stylesheet" />
        {/*  Font Awesome Icons */}
        <script src="https://kit.fontawesome.com/42d5adcbca.js" crossOrigin="anonymous"></script>
        <link href="/assets/css/nucleo-svg.css" rel="stylesheet" />
        {/*  CSS Files  */}
        <link id="pagestyle" href="/assets/css/soft-ui-dashboard.css" rel="stylesheet" />
      </head>

      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}

        {/*    Core JS Files   */}
        <script src="/assets/js/core/popper.min.js"></script>
        <script src="/assets/js/core/bootstrap.min.js"></script>
        <script src="/assets/js/plugins/perfect-scrollbar.min.js"></script>
        <script src="/assets/js/plugins/smooth-scrollbar.min.js"></script>
        {/*  Github buttons  */}
        <script async defer src="https://buttons.github.io/buttons.js"></script>
        {/*  Control Center for Soft Dashboard: parallax effects, scripts for the example pages etc */}
        <script src="/assets/js/soft-ui-dashboard.min.js"></script>
      </body>
    </html>
  );
}
