# Generated by Django 5.1.7 on 2025-03-26 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='banks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_names', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_names', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='itemGrops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_categories', models.CharField(max_length=100)),
                ('item_groups', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_names', models.CharField(max_length=100)),
                ('item_codes', models.CharField(max_length=100)),
                ('HSNSAC_codes', models.CharField(max_length=100)),
                ('sales_costs', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ledgers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledger_codes', models.CharField(max_length=50)),
                ('ledger_types', models.CharField(max_length=50)),
                ('ledger_names', models.CharField(max_length=50)),
                ('credits', models.CharField(max_length=100)),
                ('balances', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='processes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='routes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_names', models.CharField(max_length=100)),
                ('departs', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='taxs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igsts', models.CharField(max_length=100)),
                ('cgsts', models.CharField(max_length=100)),
                ('sgsts', models.CharField(max_length=100)),
            ],
        ),
    ]
