# Generated by Django 5.1.7 on 2025-03-27 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='units',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
