# Generated by Django 5.1.7 on 2025-03-27 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_items_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='taxs',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
