# Generated by Django 5.1.7 on 2025-03-27 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_items_taxs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_codes',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
