# Generated by Django 5.1.7 on 2025-03-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0004_alter_items_item_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='taxs',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='items',
            name='units',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
