# Generated by Django 5.1.7 on 2025-03-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0005_alter_items_taxs_alter_items_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_codes',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
