# Generated by Django 5.1.7 on 2025-03-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0006_alter_items_item_codes'),
    ]

    operations = [
        migrations.CreateModel(
            name='hsn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sac', models.CharField(max_length=100)),
                ('taxs', models.CharField(max_length=100)),
            ],
        ),
    ]
