# Generated by Django 5.1.7 on 2025-03-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0007_hsn'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxs',
            name='tax_names',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
