# Generated by Django 5.1.7 on 2025-03-27 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0008_taxs_tax_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxs',
            name='cgsts',
        ),
        migrations.RemoveField(
            model_name='taxs',
            name='sgsts',
        ),
    ]
