# Generated by Django 5.1.7 on 2025-03-28 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0009_remove_taxs_cgsts_remove_taxs_sgsts'),
    ]

    operations = [
        migrations.CreateModel(
            name='joborder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_names', models.CharField(max_length=100)),
                ('expected_dates', models.CharField(max_length=100)),
                ('joborders', models.CharField(max_length=100)),
                ('joborderDates', models.CharField(max_length=100)),
                ('itemCodes', models.CharField(max_length=100)),
                ('itemNames', models.CharField(max_length=100)),
                ('processNames', models.CharField(max_length=100)),
                ('qualities', models.CharField(max_length=100)),
                ('rates', models.CharField(max_length=100)),
                ('discounts', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
            ],
        ),
    ]
