# Generated by Django 5.1.7 on 2025-03-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0010_joborder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joborder',
            name='qualities',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
