# Generated by Django 5.1.7 on 2025-03-29 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0011_alter_joborder_qualities'),
    ]

    operations = [
        migrations.AddField(
            model_name='routes',
            name='inhouse',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='routes',
            name='process',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
