# Generated by Django 5.1.7 on 2025-03-29 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0012_routes_inhouse_routes_process'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=100)),
                ('jcards', models.CharField(max_length=100)),
                ('jcds', models.CharField(max_length=100)),
                ('itmcodes', models.CharField(max_length=100)),
                ('itmnames', models.CharField(max_length=100)),
                ('qtys', models.CharField(max_length=100)),
                ('depts', models.CharField(max_length=100)),
                ('pcss', models.CharField(max_length=100)),
                ('huses', models.CharField(max_length=100)),
            ],
        ),
    ]
