# Generated by Django 5.1.7 on 2025-04-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0013_jobcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Snames', models.CharField(max_length=100)),
                ('Scodes', models.CharField(max_length=100)),
                ('Divisions', models.CharField(max_length=100)),
                ('salarytypes', models.CharField(max_length=100)),
                ('worksHs', models.CharField(max_length=100)),
            ],
        ),
    ]
